Add NLVM
mohd-akram/languages pull request #10
Opened 2018-07-06 12:13 UTC by def-

Compiles Nim to LLVM IR

2018-07-06 19:17 UTC, waldyrious commented
The data in this file is actually sourced from the **[mohd-akram/compilers](https://github.com/mohd-akram/compilers)** repository. Please submit your change to the [compilers.coffee](https://github.com/mohd-akram/compilers/blob/master/src/compilers.coffee) file there, and the update should be [imported here](https://github.com/mohd-akram/languages/commits/gh-pages/js/compilers.js) shortly afterwards.

2018-07-07 16:31 UTC, mohd-akram requested changes

2018-07-07 16:31 UTC, mohd-akram commented on js/compilers.js
> +      url: 'https://nim-lang.org/'
Keep the URL changes in a separate PR.

2018-07-07 16:31 UTC, mohd-akram commented on js/compilers.js
> +      type: 'Transpiler',
Should be Intermediate.

2018-07-07 16:34 UTC, mohd-akram commented
Please open a PR in [mohd-akram/compilers](https://github.com/mohd-akram/compilers) with the requested changes. Thank you!

2018-07-07 16:34 UTC, closed without merging